### ISSUE TITLE
renameTo fails with File-Object input

### ISSUE THREAD

**Issue by jtkDvlp** [pkpkpk/cljs-node-io#3]
File Method "renameTo" fails with other input than string input (see https://github.com/pkpkpk/cljs-node-io/blob/ad5a87c452e70a9a00606eed7c33880c42065fa7/src/main/cljs_node_io/file.cljs#L176). Java File Method "renameTo" accepts File as input (see https://docs.oracle.com/javase/7/docs/api/java/io/File.html#renameTo(java.io.File))

**Comment by pkpkpk** [comment]
Thanks for this, I'll put out a fix soon
